// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(FutureVestContext))]
    [Migration("20250927194446_AjustePrecisionPesoMacroindicador")]
    partial class AjustePrecisionPesoMacroindicador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Entities.ConfiguracionRetorno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TasaMaxima")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("TasaMinima")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionRetorno", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.IndicadorPorPais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("MacroindicadorId")
                        .HasColumnType("int");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("MacroindicadorId");

                    b.HasIndex("PaisId", "MacroindicadorId", "Anio")
                        .IsUnique()
                        .HasDatabaseName("IX_Indicador_UnicoPorPaisAnio");

                    b.ToTable("IndicadoresPorPais", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.Macroindicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsMejorMasAlto")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Macroindicadores", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.SimulacionMacroindicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MacroindicadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoSimulacion")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("MacroindicadorId")
                        .IsUnique()
                        .HasDatabaseName("IX_Simulacion_UnicaPorMacroindicador");

                    b.ToTable("SimulacionMacroindicadores", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.IndicadorPorPais", b =>
                {
                    b.HasOne("Persistence.Entities.Macroindicador", "Macroindicador")
                        .WithMany("Indicadores")
                        .HasForeignKey("MacroindicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.Pais", "Pais")
                        .WithMany("Indicadores")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macroindicador");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Persistence.Entities.SimulacionMacroindicador", b =>
                {
                    b.HasOne("Persistence.Entities.Macroindicador", "Macroindicador")
                        .WithMany("Simulaciones")
                        .HasForeignKey("MacroindicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macroindicador");
                });

            modelBuilder.Entity("Persistence.Entities.Macroindicador", b =>
                {
                    b.Navigation("Indicadores");

                    b.Navigation("Simulaciones");
                });

            modelBuilder.Entity("Persistence.Entities.Pais", b =>
                {
                    b.Navigation("Indicadores");
                });
#pragma warning restore 612, 618
        }
    }
}
